### ISSUE TITLE
[request] docker image for Ubuntu 22.04

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/run-lcg-view#6]
(In lieu of a better place to put this) 

Currently there is no docker image available for Ubuntu 22.04. I think this would be nice to have. From the looks of it, there would be no changes necessary to this action itself, as long as the name is `ubuntu2204`.

**Comment by andresailer** [comment]
Is this a duplicate of https://github.com/AIDASoft/management/issues/2 ?

**Comment by tmadlener** [comment]
It most definitely is. Apologies, I forgot that there is actually a place to put this.
